frontend/controllers/CategoryController.php
<?php 
	namespace frontend\controllers;
	use yii\web\Controller;
	use yii\helpers\Html;
	use backend\models\Category;
	use backend\models\News;
	use yii\web\NotFoundHttpException;
	use yii\db\Expression;
	use yii\data\Pagination;
	use Yii;

	/**
	* 
	*/
	class CategoryController extends Controller
	{
		
		
		public function actionIndex($slug)
		{
			$cat = Category::findOne(['slug'=>$slug]);

				 $value1[] = $cat->id;

				if ($cat) {
					$catss1 = Category::find()->where(['parent'=>$cat->id])->all();
					foreach ($catss1 as $item1) {
						$value1[] = $item1->id;
					}		   	

					// lay 5 tin moi nhat
					$cate_new = News::find()->Where(['cat_id'=>$value1])->andWhere(['status'=>8])->andWhere(['public'=>1])->orderBy('id DESC')->limit(5)->all();

					//lay 6 bai ngau nhien cung chuyen muc trong 20 ngay
					$today = date('Y-m-d');
					$week = strtotime(date("Y-m-d", strtotime($today)) . " -20 day");
					$cate_rand = News::find()->Where(['cat_id'=>$value1])->andWhere(['status'=>8])->andWhere(['public'=>1])->andWhere(['>', 'created_at', '$week'])->orderBy('rand()')->limit(8)->all();

					// lay danh sach tin moi bo qua 5 tin dau
					$list_post = News::find()->Where(['cat_id'=>$value1])->andWhere(['status'=>8])->andWhere(['public'=>1])->andWhere(['<', 'id', $cate_new[4]->id])->orderBy('id DESC');
					$pages = new Pagination(['totalCount' => $list_post->count(),'defaultPageSize'=>13]);
					$list_post = $list_post->offset($pages->offset)->limit($pages->limit)->all();

					$eventnews = News::find()->Where(['cat_id'=>$value1])->andWhere(['status'=>8])->andWhere(['public'=>1])->orderBy('id DESC')->limit(15)->all();
					$dndn = News::find()->where(['status'=>8])->andWhere(['cat_id'=>62])->andWhere(['public'=>1])->limit(7)->OrderBy('id DESC')->all();
				
					return $this->render('index',[
						'cate_new'=>$cate_new,
						'cat'=>$cat,
						'list_post'=>$list_post,
						'pages'=>$pages,
						'eventnews'=>$eventnews,
						'dndn'=>$dndn,
						'cate_rand'=>$cate_rand,
					]);
				}
			  

				
			

		}
			
	}
?>

frontend/controllers/NewsController.php
<?php 
	namespace frontend\controllers;
	use yii\web\Controller;
	use yii\helpers\Html;
	use backend\models\Cat;
	use backend\models\News;
	use backend\models\Comment;
	use yii\web\NotFoundHttpException;
	use yii\db\Expression;
	use frontend\services\BaseService;

	use Yii;

	/**
	* 
	*/
	class NewsController extends Controller
	{
		public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	
		public function actionDetail($slug)
		{

			
			$newdetail = News::findOne(['slug'=>$slug]);

			 $query = Yii::$app->db->createCommand()
            ->update('news', ['view'=>$newdetail->view+1], ['slug'=>$slug])
            ->execute();

            // var_dump($newdetail)  ; die;
            $newslast =  News::find()
                ->select(['title','type_news','news.created_at as created_at','category.name AS cat_name','category.slug AS cat_slug','news.slug AS slug','view','description','images','user_id'])
                ->leftJoin('category', 'category.id = news.cat_id')
                ->andWhere(['news.status'=>8])->andWhere(['news.public'=>1])
                ->limit(6)->OrderBy('news.id DESC')->asArray()->all();

			if($newdetail->cat_id == 68){
				$videoweek = new News();
	        	$videoweek = $videoweek->getReadweek1();
				$videomoi = News::find()->where(['status'=>8])->andWhere(['cat_id'=>68])->andWhere(['public'=>1])->OrderBy('id DESC')->limit(9)->all();
				$comment = new Comment;
				return $this->render('detail_video',[
					'video'=>$newdetail,
					'videomoi'=>$videomoi,
					'videoweek'=>$videoweek,
					'comment'=>$comment,
					'newslast'=>$newslast,
				]);

			}else{
				$newdetail1 = News::find()->where(['cat_id'=>$newdetail->cat_id])->andWhere(['status'=>8])->andWhere(['public'=>1])->orderBy('id DESC')->limit(3)->all();


				 $dndn = News::find()->where(['status'=>8])->andWhere(['cat_id'=>62])->andWhere(['public'=>1])->limit(7)->OrderBy('id DESC')->all();
				// var_dump($newhot);die();->andWhere(['public'=>1])->andWhere(['public'=>1])
				
				$newlienquan =  News::find()->where(['cat_id'=>$newdetail->cat_id])->andWhere(['status'=>8])->andWhere(['public'=>1])->orderBy(new Expression('rand()'))->limit(8)->all();

				$comment = new Comment;
				return $this->render('detail',[
					'newdetail'=>$newdetail,
					'newdetail1'=>$newdetail1,
					'dndn'=>$dndn,
					'newlienquan'=>$newlienquan,
					'comment'=>$comment,
					'newslast'=>$newslast,
					// 'captcha' => [
				 //            'class' => 'yii\captcha\CaptchaAction',
				 //        ],
				]);
			}

			
		}

 public function actionComment()
	    {	     
	       $model = new Comment();

	       if($model->load(Yii::$app->request->post())){
	       	
	       	   $email = Yii::$app->request->post()['Comment']['email'];
	            if (!preg_match("/([\w\-]+\@[\w\-]+\.[\w\-]+)/", $email)) {
	                echo "error";
	            } 
	            else{

	             $model->status = 1;
	             $model->parent = 0;
	             $model->like_news = 0;
	             $model->created_at = date('Y-m-d H:i:s');
	    
			        if($model->save()){

			           echo "ok";
			        }

	            }

	   
	            

	    }

	  
	  }

  public function actionCommentparent()
    {
     
      $model = new Comment();

       if($model->load(Yii::$app->request->post())){
       	$email = Yii::$app->request->post()['Comment']['email'];
        if (!preg_match("/([\w\-]+\@[\w\-]+\.[\w\-]+)/", $email)) {
            echo "error";
        } 
        else{
    		$model->status = 1;
	       	$model->like_news = 0;
	        $model->created_at = date('Y-m-d H:i:s');
	    
	        if($model->save()){
	             echo "ok";
	        }

        }

       
      
    }
    
  
  }


  public function actionAddlike($comment_id)
    {
    	 $model = Comment::findOne($comment_id);
    	

        Yii::$app->session['like'.$comment_id] = 'like';
        
  
        if(isset(Yii::$app->session['like'.$comment_id])){
        	$query = Yii::$app->db->createCommand()
            ->update('comment', ['like_news'=>$model->like_news+1], ['id'=>$comment_id])
            ->execute();
            if($query){
             	echo "ok";
           }

        }
        
        
    }

    public function actionRemovelike($comment_id)
    {
        $model = Comment::findOne($comment_id);
        
        unset(Yii::$app->session['like'.$comment_id]); 
        if(empty(Yii::$app->session['like'.$comment_id])){
        	$query = Yii::$app->db->createCommand()
            ->update('comment', ['like_news'=>$model->like_news-1], ['id'=>$comment_id])
            ->execute();
            if($query){
             	echo "ok";
           }

        }
    }


  	 
		
	}
?>

frontend/controllers/SearchController.php
<?php 
	namespace frontend\controllers;
	use yii\web\Controller;
	use frontend\models\News;
	use yii\web\NotFoundHttpException;
	use yii\db\Expression;

	use Yii;

	/**
	* 
	*/
	class SearchController extends Controller
	{
		
		
		 public function actionSearchnew(){ 
		      $searchnew = new News;
		      $searchnew = $searchnew->getSearch(16);
		      // echo "<pre>";
		      // print_r($searchnew);die;
		      return $this->render('searchnews',
		        [
		            'searchnew'=>$searchnew['searchnews'],
		             'pages'=>$searchnew['pages'],
		        ]
	        );
	       }
	}
?>

frontend/views/layouts/comment.php
<!DOCTYPE html>
<html>
<head>
    <title> Hello</title>
</head>
<body>
<?php echo $content ?>
</body>
</html>

frontend/views/layouts/footer-mb.php
<?php
use app\components\widgets\AdsWidget;
use backend\models\Category;
use yii\helpers\Html;
use yii\helpers\Url;

?>
<footer class="footer-mb">
    <div class="border-footer_mb"></div>
    <div class="footer-mb_logo">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between">
                <a href="<?= Url::to(['/site/index'])?>" class="d-inline-block logo"><img src="../images/logo.png" alt=""></a>
                <ul class="d-flex align-items-center socical">
                    <li><a href="https://www.facebook.com/doanhnghiepvathuonghieu.com.vn/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="https://twitter.com/intent/tweet?text=<?php echo Yii::$app->params['baseUrl'] ?>"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="https://www.youtube.com/"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="border-footer_mb"></div>
    <div class="container">
        <ul class="d-flex flex-wrap footer-mb_menu">
            <?php
            $cat = new Category;
            $cat = $cat->getCategoryByParent(0, 20);
            if ($cat) :foreach ($cat as $cats) : ?>
            <li><a href="<?=  Url::to(['/category/index', 'slug' => $cats->slug]); ?>"><?= $cats->name ?></a></li>
            <?php endforeach;endif; ?>
        </ul>
    </div>
    <div class="border-footer_mb"></div>
    <div class="container">
        <div class="footer-mb-contact">
            <div class="footer-mb-contact_item">
                <h3 class="f-roboto-b t-20">Phó tổng biên tập phụ trách</h3>
                <div>Nguyễn Nam Thắng</div>
            </div>
            <div class="footer-mb-contact_item">
                <h3 class="f-roboto-b t-20">Trưởng ban điện tử</h3>
                <div>Nguyễn Nam Thắng</div>
            </div>
            <div class="footer-mb-contact_item">
                <h3 class="f-roboto-b t-20">Hợp tác quảng cáo</h3>
                <div class="mb-2">marketingTCTH@gmail.com</div>
                <a href="" class="d-inline-block f-roboto-b t-20">090.468.4321</a>
            </div>
        </div>
    </div>
    <div class="border-footer_mb"></div>
    <div class="container">
        <div class="footer-mb-address">
            <div class="d-flex align-items-start mb-1">
                <div class="mr-1 cl-00baff"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
                <div>Tầng 3 - Số 17 ngõ 167 Phố Tây Sơn, Đống Đa, Hà Nội</div>
            </div>
            <div class="d-flex align-items-center mb-1">
                <div class="mr-1 cl-7f7f7f"><i class="fa fa-envelope " aria-hidden="true"></i></div>
                <div>tapchidoanhnghiepvathuonghieu@gmail.com</div>
            </div>
            <div class="d-flex align-items-center mb-1">
                <div class="mr-1"><img src="../images/icon-phone-2.png" alt="" class="d-block w-15"></div>
                <div>024.6657.6928 - 034.333.1111</div>
            </div>
        </div>
    </div>
    <div class="border-footer_mb"></div>
    <div class="container">
        <div class="footer-mb-copyright font-italic">
            <h3 class="t-14 f-roboto-b mb-1">Bản quyền thuộc về Tạp chí Doanh nghiệp và Thương hiệu.</h3>
            <div>Mọi hành động sử dụng nội dung của doanhnghiepthuonghieu.vn phải có sự đồng ý bằng văn bản của Tạp chí Doanh nghiệp và Thương hiệu. Tạp chí Doanh nghiệp và Thương hiệu. điện tử không chịu trách nhiệm nội dung ở những trang ngoài</div>
        </div>
    </div>
</footer>
<div id="back-top"><i class="fa fa-chevron-up" aria-hidden="true"></i></div>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-155229994-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-155229994-1');
</script>

    

frontend/views/layouts/header-mb.php
<?php

use backend\models\Category;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use frontend\services\BaseService;

?>
<header class="heder-mobile mb-10">
    <div class="container position-relative">
        <div class="bg-062d3f">
            <div class="row gutter-10">
                <div class="col-5 d-flex align-items-center">
                    <?php echo Html::a('<img  src="/images/logo.png" alt="">', ['/site/index']); ?>
                </div>
                <div class="col-7">
                    <ul class="wrap-button-open-menu h-100">
                        <li><span class="f-roboto-b">Hà Nội<br><?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["low_temp"] ?> - <?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["high_temp"] ?>°C</span></li>
                        <li>
                            <button class="button-open-menu">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="wrap-menu-mobile">
    <div class="mb-filter js-mb-filter"></div>
    <div class="wrap-menu-mobile_inner js-menu-mobile">
        <button class="btn btn-sm btn-block btn-info rounded-0 js-mb-menu-close" type="button">
            <i class="fa fa-long-arrow-left"></i>
            <span>Quay lại</span>
        </button>
        <ul class="menu-mobile">
            <li class="p-10">
                <?php $form = ActiveForm::begin([
                    'method' => 'get',
                    'action' => Url::to(['search/searchnew']),
                    'options' => [
                        'class' => 'form-serach-mb'
                    ]
                ]); ?>
                <input type="text" class="form-control" name="keywords" placeholder="Tìm kiếm"/>
                <button><i class="fa fa-search"></i></button>
                <?php ActiveForm::end(); ?>
            </li>
            <?php
            $cat = new Category;
            $cat = $cat->getCategoryByParent(0, 20);
            if ($cat): foreach ($cat as $cats) : ?>
                <li>
                    <a href="<?php echo Url::to(['/category/index', 'slug' => $cats->slug]); ?>"><?= $cats->name ?> </a>
                    <?php  $cat1 = $cats->getCategoryByParent($cats->id, 20);if ($cat1): ?>
                        <span class="open-sub-menu"><i class="fa fa-angle-down"></i></span>
                        <ul class="sub-menu">
                            <?php foreach($cat1 as $cats1): ?>
                            <li>
                                <?php echo Html::a($cats1->name, ['/category/index', 'slug' => $cats1->slug, 'slugparent' => $cats->slug]); ?>
                            </li>
                            <?php endforeach;?>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endforeach;endif; ?>
        </ul>
    </div>
</div>


   
  

frontend/views/layouts/header.php
<?php

use app\components\widgets\AdsWidget;
use backend\models\Category;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use backend\models\News;
use frontend\services\BaseService;
$hotNews = News::find(['title','slug'])->andWhere(['status'=>8])->andWhere(['public'=>1])->limit(5)->OrderBy('id DESC')->all();
?>
<!--- header desktop-->
<header class="header d-none d-lg-block">
    <div class="header_top">
        <div class="container">
            <ul class="header_top_menu">
                <li><a href=""><i class="fa fa-envelope-o d-inline-block mr-1"></i>Liên hệ tòa soạn</a></li>
                <!-- <li><a href="">english</a></li> -->
            </ul>
            <?php $form = ActiveForm::begin([

                'method' => 'get',
                'action' => Url::to(['search/searchnew']),
                'options' => [
                    'class' => 'header_top_form'
                ]

            ]); ?>
            <input type="text" name="keywords" placeholder="Tìm kiếm"/>
            <button class="fa fa-search btn default btn_search"></button>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
    <div class="header_logo">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <?php echo Html::a('<img  src="/images/logo.png" alt="">', ['/site/index'], ['class' => 'd-block logo']); ?>
                </div>
                <div class="col-md-9 pl-5">
                    <?= AdsWidget::widget(["width" => "790", "height" => "100", "id" => 1]) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="header_menu menu-desktop">
        <div class="container">
            <nav class="navbar navbar-expand-lg p-0">
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav mr-auto menu">
                        <li class="nav-item">
                            <?php echo Html::a('<i class="fa fa-home t-20"></i>', ['/site/index'], ['class' => 'nav-link text-center f-roboto-b']); ?>
                        </li>
                        <?php
                        $i = 1;
                        $cat = new Category;
                        $cat = $cat->getCategoryByParent(0, 20);

                        if ($cat) {
                            foreach ($cat as $cats) {
                                if ($i > 11) break; ?>
                                <li class="nav-item">
                                <a href="<?php echo Url::to(['/category/index', 'slug' => $cats->slug]); ?>"
                                   class="nav-link f-roboto-b"><?php echo $cats->name ?> </a>
                                <?php
                                $cat1 = $cats->getCategoryByParent($cats->id, 20);
                                if ($cat1) { ?>
                                    <ul class="dropdown-menu">
                                        <?php foreach ($cat1 as $cats1) { ?>
                                            <li>
                                                <?php echo Html::a($cats1->name, ['/category/index', 'slug' => $cats1->slug, 'slugparent' => $cats->slug]); ?>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                    </li>
                                    <?php
                                }
                                $i++;
                            }
                        }
                        ?>
                        <li class="nav-item open-menu-big-destop">
                            <div class="dot-menu">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                            <div class="menu-big">
                                <div class="row">
                                    <?php
                                    if ($cat) {
                                        foreach ($cat as $cats) { ?>
                                            <div class="col-md-2 mb-3">
                                                <ul class="item-menu">
                                                    <li>
                                                        <a href="<?php echo Url::to(['/category/index', 'slug' => $cats->slug]); ?>"><?php echo $cats->name ?> </a>
                                                        <?php
                                                        $cat1 = $cats->getCategoryByParent($cats->id, 20);
                                                        if ($cat1) { ?>
                                                            <ul class="item-menu_sub">
                                                                <?php foreach ($cat1 as $cats1) { ?>
                                                                    <li class="mb-2"><?php echo Html::a($cats1->name, ['/category/index', 'slug' => $cats1->slug, 'slugparent' => $cats->slug], ['class' => 't-12']); ?></li>
                                                                <?php } ?>
                                                            </ul>
                                                        <?php } ?>
                                                    </li>
                                                </ul>
                                            </div>
                                            <?php
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="line_bottom">
            <div></div>
            <div></div>
        </div>
    </div>
</header>
<section class="top-content t-12 mb-15 mt-10 d-none d-lg-block">
    <div class="container d-flex align-item-center justify-content-between">
        <div class="left">
            <span class="d-inline-block mr-3 f-roboto-b"><?= BaseService::getDayInWeek();?>, <?= date('d').'/'.date('m').'/'.date('Y')?>, <?= date('H');?>:<?= date('i');?> (GMT+7)</span>
            <div class="d-flex align-items-center news-update">
                <span class="text-uppercase f-roboto-b label">Dòng sự kiện</span>
                <marquee direction="left" scrollamount="4" onmouseover="this.stop();" onmouseout="this.start();" >
                    <?php foreach($hotNews as $item): ?>
                    <span class="content-marquee"><a href="<?= Url::to(['news/detail','slug1'=>$item['slug']]) ?>" class="link_unstyle"><?= $item['title']?></a></span>
                    <?php endforeach;?>
                </marquee>
            </div>
        </div>
        <div class="d-flex align-items-center right">
            <div class="dropdown-weather mr-2">
                <div class="dropdown-toggle weather-current name-city" type="button" id="weather" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                    TP HÀ NỘI
                </div>
                <div class="dropdown-menu" aria-labelledby="weather">
                    <a class="dropdown-item box-city active" href="#" data-city="hn">TP HÀ NỘI</a>
                    <a class="dropdown-item box-city" href="#" data-city="hcm">TP HCM</a>
                </div>
            </div>
            <div class="d-flex align-items-end mr-2">
                <span class="f-roboto-b box-temp active" data-temp="hn"><?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["low_temp"] ?> - <?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["high_temp"] ?>°C</span>
                <span class="f-roboto-b box-temp" data-temp="hcm"><?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hcm")["low_temp"] ?> - <?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hcm")["high_temp"] ?>°C</span>
            </div>
            <div class="socical">
                <img src="../images/socical.png" alt="">
            </div>
        </div>
    </div>
</section>
<!--- end desktop -->
<!--- header mobile -->
   
<header class="heder-mobile mb-10 d-block d-lg-none">
    <div class="container position-relative">
        <div class="bg-062d3f">
            <div class="row gutter-10">
                <div class="col-5 d-flex align-items-center">
                    <?php echo Html::a('<img  src="/images/logo.png" alt="">', ['/site/index']); ?>
                </div>
                <div class="col-7">
                    <ul class="wrap-button-open-menu h-100">
                        <li><span class="f-roboto-b">Hà Nội<br><?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["low_temp"] ?> - <?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["high_temp"] ?>°C</span></li>
                        <li>
                            <button class="button-open-menu">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="wrap-menu-mobile d-block d-lg-none">
    <div class="mb-filter js-mb-filter"></div>
    <div class="wrap-menu-mobile_inner js-menu-mobile">
        <button class="btn btn-sm btn-block btn-info rounded-0 js-mb-menu-close" type="button">
            <i class="fa fa-long-arrow-left"></i>
            <span>Quay lại</span>
        </button>
        <ul class="menu-mobile">
            <li class="p-10">
                <?php $form = ActiveForm::begin([
                    'method' => 'get',
                    'action' => Url::to(['search/searchnew']),
                    'options' => [
                        'class' => 'form-serach-mb'
                    ]
                ]); ?>
                <input type="text" class="form-control" name="keywords" placeholder="Tìm kiếm"/>
                <button><i class="fa fa-search"></i></button>
                <?php ActiveForm::end(); ?>
            </li>
            <?php
            $cat = new Category;
            $cat = $cat->getCategoryByParent(0, 20);
            if ($cat): foreach ($cat as $cats) : ?>
                <li>
                    <a href="<?php echo Url::to(['/category/index', 'slug' => $cats->slug]); ?>"><?= $cats->name ?> </a>
                    <?php  $cat1 = $cats->getCategoryByParent($cats->id, 20);if ($cat1): ?>
                        <span class="open-sub-menu"><i class="fa fa-angle-down"></i></span>
                        <ul class="sub-menu">
                            <?php foreach($cat1 as $cats1): ?>
                            <li>
                                <?php echo Html::a($cats1->name, ['/category/index', 'slug' => $cats1->slug, 'slugparent' => $cats->slug]); ?>
                            </li>
                            <?php endforeach;?>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endforeach;endif; ?>
        </ul>
    </div>
</div>
<!--- end mobile -->

frontend/views/layouts/topContent.php
<?php
use backend\models\News;
use yii\helpers\Url;
use frontend\services\BaseService;
$hotNews = News::find(['title','slug'])->andWhere(['status'=>8])->andWhere(['public'=>1])->limit(5)->OrderBy('id DESC')->all();
?>
<section class="top-content t-12 mb-15 mt-10">
    <div class="container d-flex align-item-center justify-content-between">
        <div class="left">
            <span class="d-inline-block mr-3 f-roboto-b"><?= BaseService::getDayInWeek();?>, <?= date('d').'/'.date('m').'/'.date('Y')?>, <?= date('H');?>:<?= date('i');?> (GMT+7)</span>
            <div class="d-flex align-items-center news-update">
                <span class="text-uppercase f-roboto-b label">Dòng sự kiện</span>
                <marquee direction="left" scrollamount="4" onmouseover="this.stop();" onmouseout="this.start();" >
                    <?php foreach($hotNews as $item): ?>
                    <span class="content-marquee"><a href="<?= Url::to(['news/detail','slug1'=>$item['slug']]) ?>" class="link_unstyle"><?= $item['title']?></a></span>
                    <?php endforeach;?>
                </marquee>
            </div>
        </div>
        <div class="d-flex align-items-center right">
            <div class="dropdown-weather mr-2">
                <div class="dropdown-toggle weather-current name-city" type="button" id="weather" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                    TP HÀ NỘI
                </div>
                <div class="dropdown-menu" aria-labelledby="weather">
                    <a class="dropdown-item box-city active" href="#" data-city="hn">TP HÀ NỘI</a>
                    <a class="dropdown-item box-city" href="#" data-city="hcm">TP HCM</a>
                </div>
            </div>
            <div class="d-flex align-items-end mr-2">
                <span class="f-roboto-b box-temp active" data-temp="hn"><?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["low_temp"] ?> - <?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hn")["high_temp"] ?>°C</span>
                <span class="f-roboto-b box-temp" data-temp="hcm"><?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hcm")["low_temp"] ?> - <?= BaseService::getInfoWeather(\Yii::$app->params["infoWeather"],"hcm")["high_temp"] ?>°C</span>
            </div>
            <div class="socical">
                <img src="../images/socical.png" alt="">
            </div>
        </div>
    </div>
</section>